# -*- coding: utf-8 -*-
"""Tanveer Ahmed Ziad-231902048 python batch 3 final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q24Ano2wxOfQyBxayHujXzTtw--B5Qo8

question: 1
"""

import pandas as pd
from io import StringIO
data = """Name,Age,Salary,Department
Alice,25,45000,IT
Bob,30,70000,HR
Charlie,22,30000,Marketing
David,35,80000,Finance
Eva,28,50000,IT
Frank,40,120000,Engineering
Grace,32,62000,HR
Hannah,27,48000,Marketing
Ian,29,75000,Finance
Jack,26,46000,IT
Karen,31,71000,HR
Leo,38,85000,Finance
Mona,23,32000,Marketing
Nina,34,69000,HR
Oscar,45,130000,Engineering
Paul,41,110000,Engineering
Quinn,37,72000,Finance
Rachel,33,65000,Marketing
Steve,39,90000,IT
Tom,50,140000,Engineering"""

df = pd.read_csv(StringIO(data))

avg_salary_per_department = df.groupby("Department")["Salary"].mean()

highest_salary_department = avg_salary_per_department.idxmax()
highest_salary_value = avg_salary_per_department.max()

print("Average Salary Per Department:")
print(avg_salary_per_department)
print("\nDepartment with Highest Average Salary:")
print(f"{highest_salary_department}: {highest_salary_value:.2f}")

"""question 2"""

import pandas as pd

data = {
    'Region': ['East', 'West', 'East', 'West', 'South', 'North', 'East', 'West', 'South', 'North', 'South', 'Central', 'East', 'West', 'North', 'South', 'West', 'Central', 'East', 'West'],
    'Product': ['Apples', 'Bananas', 'Oranges', 'Apples', 'Oranges', 'Bananas', 'Bananas', 'Oranges', 'Apples', 'Apples', 'Bananas', 'Oranges', 'Oranges', 'Apples', 'Oranges', 'Apples', 'Bananas', 'Apples', 'Oranges', 'Apples'],
    'Sales': [5000, 7000, 4000, 6000, 3000, 9000, 8500, 7500, 6700, 7200, 5100, 8000, 4800, 5600, 4900, 6200, 7700, 9000, 5100, 7300]
}

df = pd.DataFrame(data)

sales_per_region_product = df.groupby(['Region', 'Product'])['Sales'].sum().reset_index()

print("Total Sales for Each Product in Each Region:")
print(sales_per_region_product)

total_sales_per_product = df.groupby('Product')['Sales'].sum()
highest_sales_product = total_sales_per_product.idxmax()
highest_sales_value = total_sales_per_product.max()

print("\nProduct with the Highest Total Sales Across All Regions:")
print(f"{highest_sales_product} with {highest_sales_value} total sales")

"""question: 03"""

import numpy as np

A = np.array([[2, 4, 6], [1, 3, 5], [7, 9, 11]])
B = np.array([[8, 5, 2], [7, 4, 1], [6, 3, 0]])

element_wise_sum = A + B

element_wise_product = A * B

dot_product = np.dot(A, B.T)

determinant_A = np.linalg.det(A)

print("Element-wise Sum (A + B):\n", element_wise_sum)
print("\nElement-wise Product (A * B):\n", element_wise_product)
print("\nDot Product of A and Transpose of B (A · B^T):\n", dot_product)
print("\nDeterminant of A:\n", determinant_A)

"""question:04"""

import numpy as np

data = np.random.randn(10000)

mean_value = np.mean(data)
median_value = np.median(data)
std_dev = np.std(data)

min_value = np.min(data)
max_value = np.max(data)

count_greater_than_mean = np.sum(data > mean_value)

normalized_data = (data - min_value) / (max_value - min_value)

print("Mean:", mean_value)
print("Median:", median_value)
print("Standard Deviation:", std_dev)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)
print("\nCount of values greater than the mean:", count_greater_than_mean)
print("\nFirst 10 Normalized Values:", normalized_data[:10])

"""question:05

question 5 task 1:
"""

temperatures = [28, 32, 35, 31, 29, 30, 33, 36, 27, 25, 34, 30, 29, 37, 38, 26, 31, 35, 33, 32, 36, 34, 29, 28, 27, 35, 32, 30, 31, 33]
above_32 = [temp for temp in temperatures if temp > 32]
print(above_32)

"""question 5 task:2"""

temperature_classification = [(temp, "Hot" if temp > 35 else "Warm" if 30 <= temp <= 35 else "Cool") for temp in temperatures]
print(temperature_classification)

"""question 5 task:3"""

monthly_avg = sum(temperatures) / len(temperatures)
temp_diff_from_avg = [temp - monthly_avg for temp in temperatures]
print(temp_diff_from_avg)